DELETE http://localhost:3003/api/blogs/64632f3ed50a24baf4469c24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlvbG80MjAiLCJpZCI6IjY0NjMxZWVlYzczMDEyMDgwMDg0YTBlNCIsImlhdCI6MTY4NDIyNjE1Mn0.T3wc6MC0bomG6wdaGfIYd3ISRf9pvokrYZBEPax19_4