DELETE http://localhost:3003/api/blogs/64633fe655eae715a2225569
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlvbG80MjAiLCJpZCI6IjY0NjMxZWVlYzczMDEyMDgwMDg0YTBlNCIsImlhdCI6MTY4NDIyNjE1Mn0.T3wc6MC0bomG6wdaGfIYd3ISRf9pvokrYZBEPax19_4